<!DOCTYPE html>
<html data-ng-app="backApp" lang="{{ $root.language }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?=isset($title)?'BrainCore | '.$title:'BrainCore'?></title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="/modules/Admin/public/css/bootstrap.min.css">
    <link rel="stylesheet" href="/modules/Admin/public/css/bootstrap-switch.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/modules/Admin/public/css/AdminLTE.min.css">
    <link rel="stylesheet" href="/modules/Admin/public/css/skins/skin-yellow.min.css">

    <link rel="stylesheet" href="/modules/Admin/public/css/style.css">
    <link rel="stylesheet" href="/node_modules/angular-ui-bootstrap/dist/ui-bootstrap-csp.css">
    <link rel="stylesheet" href="/node_modules/angular-ui-switch/angular-ui-switch.min.css">
    <link rel="stylesheet" href="/modules/Admin/node_modules/angular-loading-bar/src/loading-bar.css" type='text/css' media='all' >

    <link rel="stylesheet" href="/modules/Admin/node_modules/ng-datepicker/src/css/ngDatepicker.css">
    <link rel="stylesheet" href="/modules/Admin/public/css/cropper.css">
    <link rel="stylesheet" href="/modules/Admin/public/css/main.css">

    <!---->
    <link rel="stylesheet" href="/modules/Admin/bower_components/ng-img-crop/compile/minified/ng-img-crop.css">
    <!---->

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body class="hold-transition skin-yellow sidebar-mini" data-ng-controller="CommonController as ctrl">
<div class="wrapper" data-ng-init="ctrl.langInit('<?=$defaultLang?>')">

    <!-- Main Header -->
    <header class="main-header">

        <!-- Logo -->
        <a data-ng-href="/admin" target="_self" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>B</b>nC</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Brain</b>CORE</span>
        </a>

        <!-- Header Navbar -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
            <!-- Navbar Right Menu -->
            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                    <!-- User Account Menu -->
                    <li class="dropdown user user-menu">
                        <!-- Menu Toggle Button -->
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <!-- The user image in the navbar-->
                            <img src="<?=$cover?>" class="user-image" alt="User Image">
                            <!-- hidden-xs hides the username on small devices so only the image appears. -->
                            <span class="hidden-xs">Teszt Krisz Thing</span>
                        </a>
                        <ul class="dropdown-menu">
                            <!-- The user image in the menu -->
                            <li class="user-header">
                                <img src="<?=$cover?>" class="img-circle" alt="User Image">
                                <p>
                                    Teszt full Krisz name- Web Developer
                                    <small>Member since Nov. 2012</small>
                                </p>
                            </li>
                            <!-- Menu Body -->
                            <li class="user-body">
                                <div class="col-xs-4 text-center">
                                    <a href="#">{{'followers'|translate}}</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">{{'sales'|translate}}</a>
                                </div>
                                <div class="col-xs-4 text-center">
                                    <a href="#">{{'friends'|translate}}</a>
                                </div>
                            </li>
                            <!-- Menu Footer-->
                            <li class="user-footer">
                                <div class="pull-left">
                                    <a href="#" class="btn btn-default btn-flat">{{'profile'|translate}}</a>
                                </div>
                                <div class="pull-right">
                                   <logout-button></logout-button>
                                </div>
                            </li>
                        </ul>
                    </li>
                    <!-- Control Sidebar Toggle Button -->
                    <li>
                        <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">

            <!-- Sidebar user panel (optional) -->
            <div class="user-panel">
                <div class="pull-left image">
                    <img src="<?=$cover?$cover:'/modules/Admin/public/img/user.jpg'?>" class="img-circle" alt="User Image">
                </div>
                <div class="pull-left info">
                    <p>Fullname</p>
                    <!-- Status -->
                    <a href="#"><i class="fa fa-circle text-success"></i>{{'online'|translate}}</a>
                </div>
            </div>

            <!-- search form (Optional) -->
            <form action="#" method="get" class="sidebar-form">
                <div class="input-group">
                    <input type="text" name="q" class="form-control" placeholder="Search..." autocomplete="off">
              <span class="input-group-btn">
                <button type="submit" name="{{'search'|translate}}" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
                </div>
            </form>
            <!-- /.search form -->

            <!-- Sidebar Menu -->
            <ul class="sidebar-menu">
                <li class="header">HEADER</li>
                <!-- Optionally, you can add icons to the links -->

                    <li class="treeview" data-ng-show="ctrl.hasPermission('rights')">
                        <a href="#"><i class="fa fa-gears"></i> <span>{{'rights'|translate}}</span> <i class="fa fa-angle-left pull-right"></i></a>
                        <ul class="treeview-menu">
                            <li data-ng-show="ctrl.hasPermission('rights.user')"><a href="/admin/right">{{'user-rights'|translate}}</a></li>
                            <li data-ng-show="ctrl.hasPermission('rights.roles')"><a href="/admin/role">{{'roles'|translate}}</a></li>
                        </ul>
                    </li>

                    <li class="treeview" data-ng-show="ctrl.hasPermission('cms')">
                        <a href="#"><i class="fa fa-files-o"></i> <span>{{'contents'|translate}}</span> <i class="fa fa-angle-left pull-right"></i></a>
                        <ul class="treeview-menu">
                            <li data-ng-show="ctrl.hasPermission('cms.content')"><a href="/admin/content">{{'handle-content'|translate}}</a></li>
                            <li data-ng-show="ctrl.hasPermission('cms.labels')"><a href="/admin/label">{{'handle-labels'|translate}}</a></li>
                        </ul>
                    </li>

                    <li data-ng-show="ctrl.hasPermission('partner')">
                        <a href="/admin/partner">
                            <i class="fa fa-male"></i> <span>{{'partners'|translate}}</span>
                        </a>
                    </li>

                    <li class="treeview" data-ng-show="ctrl.hasPermission('product')">
                        <a href="#"><i class="fa fa-shopping-cart"></i> <span>{{'products'|translate}}</span> <i class="fa fa-angle-left pull-right"></i></a>
                        <ul class="treeview-menu">
                            <li><a href="/admin/product">{{'upload'|translate}}</a></li>
                            <li><a href="/admin/prodcateg">{{'categories'|translate}}</a></li>
                            <li><a href="/admin/discount">{{'discounts'|translate}}</a></li>
                        </ul>
                    </li>

                    <li data-ng-show="ctrl.hasPermission('storage')">
                        <a href="/admin/storage">
                            <i class="fa fa-star-half-full"></i> <span>{{'storage'|translate}}</span>
                        </a>
                    </li>

                    <li data-ng-show="ctrl.hasPermission('language')">
                        <a href="/admin/language">
                            <i class="fa fa-globe"></i> <span>{{'languages'|translate}}</span>
                        </a>
                    </li>

                    <li>
                        <a href="/admin/master">
                            <i class="fa fa-heartbeat"></i> <span>{{'master'|translate}}</span>
                        </a>
                    </li>

            </ul>
        </section>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Title , Description, array(Breadcumbs) -->
        <section class="content-header">

        </section>

        <!-- Main content -->
        <section class="content">
            <div data-ng-view></div>
            <?/*=$this->getContent()*/?>
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    <!-- Main Footer -->
    <footer class="main-footer">
        <!-- To the right -->
        <div class="pull-right hidden-xs">
            {{'footer-slogan'|translate}}
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; <?php echo date("Y"); ?> <a data-ng-href="/admin">BrainCore</a>.</strong> {{'all-right-reserved'|translate}}
    </footer>

    <!-- Control Sidebar -->
    <aside class="control-sidebar control-sidebar-dark">
        <!-- Create the tabs -->
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
            <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
            <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
            <!-- Home tab content -->
            <div class="tab-pane active" id="control-sidebar-home-tab">
                <h3 class="control-sidebar-heading">{{'recent-activity'|translate}}</h3>
                <ul class="control-sidebar-menu">
                    <li>
                        <a href="#">
                            <i class="menu-icon fa fa-birthday-cake bg-red"></i>
                            <div class="menu-info">
                                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
                                <p>Will be 23 on April 24th</p>
                            </div>
                        </a>
                    </li>
                </ul><!-- /.control-sidebar-menu -->

                <h3 class="control-sidebar-heading">{{'task-progress'|translate}}</h3>
                <ul class="control-sidebar-menu">
                    <li>
                        <a href="javascript::;">
                            <h4 class="control-sidebar-subheading">
                                Custom Template Design
                                <span class="label label-danger pull-right">70%</span>
                            </h4>
                            <div class="progress progress-xxs">
                                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                            </div>
                        </a>
                    </li>
                </ul><!-- /.control-sidebar-menu -->

            </div><!-- /.tab-pane -->
            <!-- Stats tab content -->
            <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div><!-- /.tab-pane -->
            <!-- Settings tab content -->
            <div class="tab-pane" id="control-sidebar-settings-tab">
                <form method="post">
                    <h3 class="control-sidebar-heading">{{'languages'|translate}}</h3>
                    <div class="pointer" data-ng-repeat="lang in ctrl.commonService.langs" data-ng-click="ctrl.changeLang(lang.code)">{{lang.name}}</div>
                    <h3 class="control-sidebar-heading">{{'general-settings'|translate}}</h3>
                    <div class="form-group">
                        <label class="control-sidebar-subheading">
                            {{'report-panel-usage'|translate}}
                            <input type="checkbox" class="pull-right" checked>
                        </label>
                        <p>
                            {{'general-option-info'|translate}}
                        </p>
                    </div><!-- /.form-group -->
                </form>
            </div><!-- /.tab-pane -->
        </div>
    </aside>
    <div class="control-sidebar-bg"></div>
</div><!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->
<!-- jQuery 2.1.4 -->
<script src="/modules/Admin/public/js/jQuery-2.1.4.min.js"></script>
<!-- Bootstrap 3.3.5 -->
<script src="/modules/Admin/public/js/bootstrap-switch.js"></script>
<script src="/modules/Admin/public/js/bootstrap.min.js"></script>
<!-- AdminLTE App -->
<script src="/modules/Admin/public/js/enscroll.min.js"></script>
<script src="/modules/Admin/public/js/app.min.js"></script>
<script src="/modules/Admin/public/js/jquery.Jcrop.min.js"></script>
<script src="/modules/Admin/public/js/tools.js"></script>
<script src="/modules/Admin/public/js/cropper.js"></script>
<script src="/modules/Admin/bower_components/angular/angular.js"></script>
<script src="/node_modules/angular-ui-bootstrap/dist/ui-bootstrap.js"></script>
<script src="/modules/Admin/bower_components/angular-route/angular-route.js"></script>
<script src="/modules/Admin/bower_components/angular-local-storage/dist/angular-local-storage.js"></script>
<script src="/modules/Admin/bower_components/angular-translate/angular-translate.js"></script>
<script src="/modules/Admin/bower_components/angular-translate-loader-static-files/angular-translate-loader-static-files.min.js"></script>
<!-- ANGULAR IMAGE CROPPER -->
<script src="/modules/Admin/bower_components/ng-img-crop/compile/minified/ng-img-crop.js"></script>
<script src="/modules/Admin/bower_components/angular-img-cropper/dist/angular-img-cropper.min.js"></script>
<!-- ANGULAR IMAGE CROPPER END -->
<script src="/modules/Admin/node_modules/angular-loading-bar/src/loading-bar.js"></script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment-with-locales.min.js"></script>
<script type="text/javascript" src="/modules/Admin/node_modules/ng-datepicker/src/js/ngDatepicker.min.js"></script>
<script src="/modules/Admin/bower_components/angular-smart-table/dist/smart-table.min.js"></script>
<script src="/node_modules/angular-ui-switch/angular-ui-switch.min.js"></script>
<script src="/modules/Admin/bower_components/angular-modal-service/dst/angular-modal-service.min.js"></script>
<script src="/modules/Admin/backend-scripts.js"></script>
</body>
</html>
