<!DOCTYPE html>
<html data-ng-app="backApp">
<head>
    <link rel="stylesheet" type="text/css" href="/modules/Admin/public/css/mainstyle.css">
    <script src="/node_modules/angular-ui-bootstrap/dist/ui-bootstrap-csp.css"></script>
    <link rel="stylesheet" href="/modules/Admin/node_modules/angular-loading-bar/src/loading-bar.css" type='text/css' media='all' >
    <title>Login</title>
</head>
<body>
<header>

</header>
<!-- Main content -->
<login-form></login-form>
<footer>
    <!-- REQUIRED JS SCRIPTS -->
    <script src="/modules/Admin/bower_components/angular/angular.js"></script>
    <script src="/modules/Admin/bower_components/angular-route/angular-route.js"></script>
    <script src="/modules/Admin/bower_components/angular-local-storage/dist/angular-local-storage.js"></script>
    <script src="/modules/Admin/bower_components/angular-smart-table/dist/smart-table.min.js"></script>

    <script src="/modules/Admin/bower_components/angular-translate/angular-translate.js"></script>
    <script src="/modules/Admin/bower_components/angular-translate-loader-static-files/angular-translate-loader-static-files.min.js"></script>
    
    <script src="/modules/Admin/bower_components/angular-img-cropper/dist/angular-img-cropper.min.js"></script>
    <script src="/node_modules/angular-ui-switch/angular-ui-switch.min.js"></script>
    <script src="/node_modules/angular-ui-bootstrap/dist/ui-bootstrap.js"></script>
    <script src="/modules/Admin/node_modules/angular-loading-bar/src/loading-bar.js"></script>
    <script src="/modules/Admin/backend-scripts.js"></script>
</footer>
</body>
</html>